# Let NetworkManager manage all devices on this system
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      addresses:
        -  192.168.100.5/24
      nameservers:
        addresses: [192.168.100.5,1.1.1.1]
      routes:
        - to: default
          via: 192.168.100.1
