logger:
  file: /root/open5gs/install/var/log/open5gs/upf.log
#  level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
#   peer: 64

upf:
  pfcp:
    server:
      - address: 192.168.64.60
#    client:
 #    smf:     #  UPF PFCP Client try to associate SMF PFCP Server
  #      - address: 127.0.0.24
  gtpu:
    server:
      - address: 192.168.64.60
  # session:
  #   - subnet: 10.45.0.1/16
   #   dnn: video-streaming
  session:
    - subnet: 10.45.0.1/16
      dnn: internet
      dev: ogstun
  metrics:
    server:
      - address: 127.0.0.7
        port: 9090
