# /etc/netplan/01-netcfg.yaml

network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s1:
      addresses:
        - 192.168.64.20/24
      gateway4: 192.168.0.1  # Make sure to adjust the gateway address accordingly
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]  # Optional: DNS server addresses

